"""Create product galery table

Revision ID: f233c9cea638
Revises: f15518872c8d
Create Date: 2022-08-12 07:41:44.242152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f233c9cea638'
down_revision = 'f15518872c8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_galery',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=True),
    sa.Column('title', sa.String(length=50), nullable=True),
    sa.Column('path', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_galery')
    # ### end Alembic commands ###
